import puppeteer from "puppeteer";
import fs from 'fs'
import fetch from "node-fetch";

const urls = [
  "/problems/gas-station",
  "/problems/majority-element",
  "/problems/distribute-candy",
  "/problems/longest-increasing-subsequence",
  "/problems/unique-binary-search-trees",
  "/problems/max-rectangle-in-binary-matrix",
  "/problems/distinct-subsequences",
  "/problems/unique-paths-in-a-grid",
  "/problems/max-product-subarray",
  "/problems/ways-to-decode",
  "/problems/best-time-to-buy-and-sell-stocks-ii",
  "/problems/best-time-to-buy-and-sell-stocks-iii",
  "/problems/best-time-to-buy-and-sell-stocks-i",
  "/problems/max-sum-path-in-binary-tree",
  "/problems/regular-expression-match",
  "/problems/palindrome-partitioning-ii",
  "/problems/min-sum-path-in-matrix",
  "/problems/min-jumps-array",
  "/problems/edit-distance",
  "/problems/unique-binary-search-trees-ii",
  "/problems/word-break",
  "/problems/regular-expression-ii",
  "/problems/jump-game-array",
  "/problems/interleaving-strings",
  "/problems/word-break-ii",
  "/problems/longest-valid-parentheses",
  "/problems/stairs",
  "/problems/swap-list-nodes-in-pairs",
  "/problems/rotate-list",
  "/problems/reorder-list",
  "/problems/sort-list",
  "/problems/remove-duplicates-from-sorted-list-ii",
  "/problems/merge-two-sorted-lists",
  "/problems/remove-duplicates-from-sorted-list",
  "/problems/add-two-numbers-as-lists",
  "/problems/remove-nth-node-from-list-end",
  "/problems/partition-list",
  "/problems/insertion-sort-list",
  "/problems/list-cycle",
  "/problems/intersection-of-linked-lists",
  "/problems/reverse-link-list-ii",
  "/problems/evaluate-expression",
  "/problems/rain-water-trapped",
  "/problems/generate-all-parentheses",
  "/problems/largest-rectangle-in-histogram",
  "/problems/sliding-window-maximum",
  "/problems/simplify-directory-path",
  "/problems/min-stack",
  "/problems/kth-row-of-pascals-triangle",
  "/problems/rotate-matrix",
  "/problems/max-sum-contiguous-subarray",
  "/problems/find-duplicate-in-array",
  "/problems/merge-intervals",
  "/problems/spiral-order-matrix-i",
  "/problems/repeat-and-missing-number-array",
  "/problems/merge-overlapping-intervals",
  "/problems/set-matrix-zeros",
  "/problems/spiral-order-matrix-ii",
  "/problems/largest-number",
  "/problems/first-missing-integer",
  "/problems/add-one-to-number",
  "/problems/n3-repeat-number",
  "/problems/pascal-triangle",
  "/problems/maximum-consecutive-gap",
  "/problems/max-distance",
  "/problems/next-permutation",
  "/problems/palindrome-integer",
  "/problems/excel-column-number",
  "/problems/reverse-integer",
  "/problems/excel-column-title",
  "/problems/grid-unique-paths",
  "/problems/trailing-zeros-in-factorial",
  "/problems/monkeys-and-doors",
  "/problems/daughters-ages",
  "/problems/jelly-beans-jars",
  "/problems/cross-the-bridge",
  "/problems/the-tribe",
  "/problems/divide-the-cake",
  "/problems/make-a-statement",
  "/problems/find-the-defective-ball",
  "/problems/prisoners-and-poison",
  "/problems/world-trips",
  "/problems/color-of-the-bear",
  "/problems/one-mile-on-the-globe",
  "/problems/divide-gold-bar",
  "/problems/quarters-on-a-table",
  "/problems/measure-milk-by-cans",
  "/problems/light-switches-in-the-cellar",
  "/problems/next-number-ii",
  "/problems/eggs-and-building",
  "/problems/ants-on-a-triangle",
  "/problems/all-unique-permutations",
  "/problems/kth-permutation-sequence",
  "/problems/combination-sum",
  "/problems/permutations",
  "/problems/generate-all-parentheses-ii",
  "/problems/combination-sum-ii",
  "/problems/nqueens",
  "/problems/combinations",
  "/problems/sudoku",
  "/problems/gray-code",
  "/problems/subsets-ii",
  "/problems/letter-phone",
  "/problems/subset",
  "/problems/palindrome-partitioning",
  "/problems/substring-concatenation",
  "/problems/window-string",
  "/problems/longest-consecutive-sequence",
  "/problems/4-sum",
  "/problems/anagrams",
  "/problems/fraction",
  "/problems/points-on-the-straight-line",
  "/problems/2-sum",
  "/problems/valid-sudoku",
  "/problems/copy-list",
  "/problems/diffk-ii",
  "/problems/longest-substring-without-repeat",
  "/problems/diffk",
  "/problems/intersection-of-sorted-arrays",
  "/problems/merge-two-sorted-lists-ii",
  "/problems/3-sum",
  "/problems/remove-duplicates-from-sorted-array",
  "/problems/sort-by-color",
  "/problems/array-3-pointers",
  "/problems/container-with-most-water",
  "/problems/3-sum-zero",
  "/problems/remove-duplicates-from-sorted-array-ii",
  "/problems/remove-element-from-array",
  "/problems/implement-strstr",
  "/problems/integer-to-roman",
  "/problems/longest-common-prefix",
  "/problems/roman-to-integer",
  "/problems/length-of-last-word",
  "/problems/multiply-strings",
  "/problems/valid-number",
  "/problems/zigzag-string",
  "/problems/atoi",
  "/problems/valid-ip-addresses",
  "/problems/compare-version-numbers",
  "/problems/longest-palindromic-substring",
  "/problems/pretty-json",
  "/problems/count-and-say",
  "/problems/justified-text",
  "/problems/add-binary-strings",
  "/problems/reverse-the-string",
  "/problems/reverse-bits",
  "/problems/number-of-1-bits",
  "/problems/single-number",
  "/problems/divide-integers",
  "/problems/single-number-ii",
  "/problems/median-of-array",
  "/problems/search-for-a-range",
  "/problems/square-root-of-integer",
  "/problems/implement-power-function",
  "/problems/rotated-array",
  "/problems/rotated-sorted-array-search",
  "/problems/sorted-insert-position",
  "/problems/convert-sorted-list-to-binary-search-tree",
  "/problems/level-order",
  "/problems/capture-regions-on-board",
  "/problems/word-ladder-ii",
  "/problems/clone-graph",
  "/problems/word-search-board",
  "/problems/word-ladder-i",
  "/problems/inorder-traversal",
  "/problems/recover-binary-search-tree",
  "/problems/inorder-traversal-of-cartesian-tree",
  "/problems/least-common-ancestor",
  "/problems/construct-binary-tree-from-inorder-and-preorder",
  "/problems/flatten-binary-tree-to-linked-list",
  "/problems/valid-binary-search-tree",
  "/problems/preorder-traversal",
  "/problems/max-depth-of-binary-tree",
  "/problems/binary-tree-from-inorder-and-postorder",
  "/problems/balanced-binary-tree",
  "/problems/sorted-array-to-balanced-bst",
  "/problems/sum-root-to-leaf-numbers",
  "/problems/symmetric-binary-tree",
  "/problems/postorder-traversal",
  "/problems/populate-next-right-pointers-tree",
  "/problems/identical-binary-trees",
  "/problems/bst-iterator",
  "/problems/zigzag-level-order-traversal-bt",
  "/problems/path-sum",
  "/problems/next-pointer-binary-tree",
  "/problems/min-depth-of-binary-tree",
  "/problems/root-to-leaf-paths-with-sum",
  "/problems/merge-k-sorted-lists",
  "/problems/lru-cache",
  "/problems/nestedcmpl3",
  "/problems/spiders-web",
  "/problems/ratio-of-boys-and-girls",
  "/problems/max-non-negative-subarray",
  "/problems/wave-array",
  "/problems/rearrange-array",
  "/problems/greatest-common-divisor",
  "/problems/allocate-books",
  "/problems/painters-partition-problem",
  "/problems/power-of-2",
  "/problems/max-continuous-series-of-1s",
  "/problems/redundant-braces",
  "/problems/colorful-number",
  "/problems/order-of-people-heights",
  "/problems/shortest-unique-prefix",
  "/problems/max-sum-without-adjacent-elements",
  "/problems/repeating-subsequence",
  "/problems/evaluate-expression-to-true",
  "/problems/seats",
  "/problems/stepping-numbers",
  "/problems/equal",
  "/problems/highest-product",
  "/problems/assign-mice-to-holes",
  "/problems/black-shapes",
  "/problems/knight-on-chess-board",
  "/problems/anti-diagonals",
  "/problems/hotel-bookings-possible",
  "/problems/min-steps-in-infinite-grid",
  "/problems/power-of-two-integers",
  "/problems/prime-sum",
  "/problems/largest-continuous-sequence-zero-sum",
  "/problems/arrange-ii",
  "/problems/equal-average-partition",
  "/problems/sorted-permutation-rank",
  "/problems/sorted-permutation-rank-with-repeats",
  "/problems/coin-sum-infinite",
  "/problems/flip",
  "/problems/different-bits-sum-pairwise",
  "/problems/palindrome-list",
  "/problems/nearest-smaller-element",
  "/problems/distinct-numbers-in-window",
  "/problems/invert-the-binary-tree",
  "/problems/kth-smallest-element-in-tree",
  "/problems/2sum-binary-tree",
  "/problems/rod-cutting",
  "/problems/smallest-multiple-with-0-and-1",
  "/problems/find-permutation",
  "/problems/maximum-absolute-difference",
  "/problems/matrix-median",
  "/problems/maximum-unsorted-subarray",
  "/problems/minimum-characters-required-to-make-a-string-palindromic",
  "/problems/longest-arithmetic-progression",
  "/problems/ways-to-form-max-heap",
  "/problems/sum-of-pairwise-hamming-distance",
  "/problems/sub-matrices-with-sum-zero",
  "/problems/largest-distance-between-nodes-of-a-tree",
  "/problems/length-of-longest-subsequence",
  "/problems/shortest-common-superstring",
  "/problems/smallest-sequence-with-given-primes",
  "/problems/commutable-islands",
  "/problems/possibility-of-finishing-all-courses-given-prerequisites",
  "/problems/vertical-order-traversal-of-binary-tree",
  "/problems/k-reverse-linked-list",
  "/problems/ways-to-color-a-3xn-board",
  "/problems/min-xor-value",
  "/problems/tushars-birthday-party",
  "/problems/kth-manhattan-distance-neighbourhood",
  "/problems/n-max-pair-combinations",
  "/problems/valid-path",
  "/problems/minimize-the-absolute-difference",
  "/problems/largest-area-of-rectangle-with-permutations",
  "/problems/hotel-reviews",
  "/problems/partitions",
  "/problems/multiple-left-rotations-of-the-array",
  "/problems/find-a-peak-element",
  "/problems/first-non-repeating-character-in-a-stream-of-characters",
  "/problems/longest-common-subsequence",
  "/problems/longest-palindromic-subsequence",
  "/problems/best-time-to-buy-and-sell-stock-atmost-b-times",
  "/problems/meeting-rooms",
  "/problems/right-view-of-binary-tree",
  "/problems/valid-bst-from-preorder",
  "/problems/diagonal-traversal",
  "/problems/maximum-sum-combinations",
  "/problems/maximum-path-in-triangle",
  "/problems/cousins-in-binary-tree",
  "/problems/reverse-alternate-k-nodes",
  "/problems/kth-node-from-middle",
  "/problems/pair-with-given-difference",
  "/problems/path-to-given-node",
  "/problems/count-total-set-bits",
  "/problems/sort-binary-linked-list",
  "/problems/cycle-in-directed-graph",
  "/problems/k-largest-elements",
  "/problems/palindromic-binary-representation",
  "/problems/remove-half-nodes",
  "/problems/cycle-in-undirected-graph",
  "/problems/next-similar-number",
  "/problems/convert-to-palindrome",
  "/problems/0-1-knapsack",
  "/problems/chain-of-pairs",
  "/problems/merge-two-binary-tree",
  "/problems/maximum-ones-after-modification",
  "/problems/is-rectangle",
  "/problems/snake-ladder-problem",
  "/problems/region-in-binarymatrix",
  "/problems/balanced-parantheses",
  "/problems/pairs-with-given-xor",
  "/problems/maximum-size-square-sub-matrix",
  "/problems/min-cost-path",
  "/problems/minimum-lights-to-activate",
  "/problems/two-teams",
  "/problems/even-reverse",
  "/problems/minimum-appends-for-palindrome",
  "/problems/maximal-string",
  "/problems/an-increment-problem",
  "/problems/large-factorial",
  "/problems/remove-consecutive-characters",
  "/problems/permutation-swaps",
  "/problems/delete-edge",
  "/problems/maximum-sum-triplet",
  "/problems/find-nth-fibonacci",
  "/problems/maximum-sum-square-submatrix",
  "/problems/maximum-area-of-triangle",
  "/problems/profit-maximisation",
  "/problems/perfect-peak-of-array",
  "/problems/subarray-with-given-xor",
  "/problems/two-out-of-three",
  "/problems/subarray-with-b-odd-numbers",
  "/problems/tiling-with-dominoes",
  "/problems/reverse-level-order",
  "/problems/woodcutting-made-easy",
  "/problems/useful-extra-edges",
  "/problems/largest-permutation",
  "/problems/increasing-path-in-matrix",
  "/problems/minimum-parantheses",
  "/problems/leaders-in-an-array",
  "/problems/trailing-zeroes",
  "/problems/maximum-edge-removal",
  "/problems/search-in-bitonic-array",
  "/problems/egg-drop-problem",
  "/problems/step-by-step",
  "/problems/next-smallest-palindrome",
  "/problems/distribute-in-circle",
  "/problems/total-moves-for-bishop",
  "/problems/subarray-with-equal-occurences",
  "/problems/paint-house",
  "/problems/maximum-level-sum",
  "/problems/pick-from-both-sides",
  "/problems/merge-k-sorted-arrays",
  "/problems/minimum-difference-subsets",
  "/problems/sort-array-with-squares",
  "/problems/counting-subarrays",
  "/problems/subset-sum-problem",
  "/problems/xor-ing-the-subarrays",
  "/problems/longest-subarray-length",
  "/problems/first-repeating-element",
  "/problems/merge-elements",
  "/problems/balance-array",
  "/problems/max-min-05542f2f-69aa-4253-9cc7-84eb7bf739c4",
  "/problems/subarrays-with-distinct-integers",
  "/problems/path-in-directed-graph",
  "/problems/path-with-good-nodes",
  "/problems/xor-between-two-arrays",
  "/problems/max-edge-queries",
  "/problems/disjoint-intervals",
  "/problems/water-flow",
  "/problems/burn-a-tree",
  "/problems/nodes-at-distance-k",
  "/problems/reorder-data-in-log-files",
  "/problems/k-th-permutation",
  "/problems/vertical-sum-of-a-binary-tree",
  "/problems/serialize",
  "/problems/deserialize",
  "/problems/string-and-its-frequency",
  "/problems/move-zeroes",
  "/problems/make-equal-elements-array",
  "/problems/segregate-0s-and-1s-in-an-array",
  "/problems/capacity-to-ship-packages-within-b-days",
  "/problems/bulls-and-cows",
  "/problems/construct-bst-from-preorder",
  "/problems/covered-uncovered-nodes",
  "/problems/self-permutation",
  "/problems/potions",
  "/problems/last-node-in-a-complete-binary-tree",
  "/problems/array-sum",
  "/problems/mother-vertex",
  "/problems/dice-throw",
  "/problems/set-intersection",
  "/problems/divisible-by-60",
  "/problems/powerful-divisors",
  "/problems/path-in-matrix",
  "/problems/consecutive-parent-child",
  "/problems/addition-without-summation",
  "/problems/hotel-service",
  "/problems/all-possible-combinations",
  "/problems/occurence-of-each-number",
  "/problems/highest-score",
  "/problems/file-search",
  "/problems/salutes"
]

function saveImageToDisk(url, filename) {
  fetch(url)
    .then(res => {
      const dest = fs.createWriteStream(filename);
      res.body.pipe(dest)
    })
    .catch((err) => {
      console.log(err)
    })
}

(async () => {
  const host = 'https://www.interviewbit.com'
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  for (const url of urls) {
    console.log(`scrapping: ${host + url}`);
    await page.goto(host + url);
    await page.waitForTimeout(2000);

    let {title, body, images} = await page.evaluate(() => {
      let els = document.querySelectorAll('.sr-backdrop, .sr-modal, .sr-modal--right')
      for (let i = 0; i < els.length; i++) {
        els[i].parentNode.removeChild(els[i]);
      }

      let title = document.querySelector('.p-tile__title').innerText.replaceAll("/", "-slash-").replaceAll(".", "").replaceAll("\n", "").trim()
      let images = []
      Array.from(document.querySelectorAll('.p-html-content__container img')).map(img => {
        let src = img.src
        let srcArray = src.split('/')
        let pos = srcArray.length - 1
        let filename = srcArray[pos]
        images.push({
          src,
          filename
        })
      })
      let body = document.querySelectorAll('.p-html-content__container')[0].parentElement.parentElement.innerHTML.replace(/<img [^>]*src=['"]([^'"]+)[^>]*>/gi, function (match) {
        return match.replace(/<img([^>]*)\ssrc=(['"])(?:[^\2\/]*\/)*([^\2]+)\2/gi, "<img$1 src=$2images/$3$2");
      }).trim();

      return {title, images, body}
    })

    let text = `<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>${title}</title>
    <link rel="stylesheet" media="screen" href="css/style.css">
</head>
<body>
  <div id="react">
    <div class="react-root">
        <div class="interviewbit">
        ${body}
        </div>
    </div>
  </div>
</body>
</html>
`

    images.map((image) => {
      let filename = `./problems/interviewbit/images/${image.filename}`
      saveImageToDisk(image.src, filename)
    })
    fs.writeFileSync(`problems/interviewbit/${title}.html`, text);
  }

  await browser.close();
})();
